#!/bin/bash

# Change these as appropriate
IMAGE_NAME="directorate-api"
CONTAINER_NAME="directorate-api-container"

# Paths to certificates generated by Certbot
CERT_PATH="/etc/letsencrypt/live/the-directorate.com/fullchain.pem"
KEY_PATH="/etc/letsencrypt/live/the-directorate.com/privkey.pem"

# Stop and remove old container if it exists
if [ "$(docker ps -aq -f name=$CONTAINER_NAME)" ]; then
    echo "Stopping and removing previous container ($CONTAINER_NAME)..."
    docker stop $CONTAINER_NAME
    docker rm $CONTAINER_NAME
fi

# Build the Docker image
echo "Building Docker image ($IMAGE_NAME)..."
docker image prune -f
docker build -t $IMAGE_NAME .

# Run the container, mounting certs
echo "Running new Docker container on port 443 with SSL certs mounted..."
docker run -d -p 443:443 \
    --name $CONTAINER_NAME \
    -v $CERT_PATH:/etc/ssl/fullchain.pem:ro \
    -v $KEY_PATH:/etc/ssl/privkey.pem:ro \
    $IMAGE_NAME

echo "API deployment complete!"
